name: Work Stats README
on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"

jobs:
 update-readme:
   name: Update this repo's README with recent activity
   runs-on: ubuntu-latest
   permissions:
     contents: write
   steps:
    - uses: actions/checkout@v3
    - uses: athul/waka-readme@master
    - run: |
          go install github.com/muesli/markscribe@master
          markscribe ./templates/README.md.tpl > README.md
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        WAKATIME_API_KEY:
          ${{secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 5
          COMMIT_MESSAGE: "Updated waka-readme graph with new metrics"
          SECTION_NAME: WAKA
          commit_message: "update activity"
          branch: master
          commit_user_name: readme-scribe 🤖
          commit_user_email: "102756485+Chunnyluny@users.noreply.github.com"
          commit_author: readme-scribe 🤖 <"102756485+Chunnyluny@users.noreply.github.com">
