name: readme-scribe
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 */1 * * *

jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ^1
      - run: |
          go install muesli/readme-scribe@v0.1
        shell: bash

      - name: Generate & update markdown content
        uses: muesli/readme-scribe@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          template: templates/README.md.tpl
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: master
          commit_user_name: readme-scribe 🤖
          commit_user_email: 102756485+Chunnyluny@users.noreply.github.com
          commit_author: readme-scribe 🤖 <"102756485+Chunnyluny@users.noreply.github.com">
