# @format

name: Update README
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * 1-5"
    - cron: "0 */6 * * 1-5"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1"
      - run: |
          go install github.com/muesli/markscribe@master
          markscribe ./templates/README.md.tpl > README.md
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 5
          COMMIT_MESSAGE: "Updated README with new metrics"
          SECTION_NAME: WAKA
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          commit_message: "updating info with recent activity"
          branch: master
          commit_user_name: readme-scribe 🤖
          commit_user_email: "102756485+Chunnyluny@users.noreply.github.com"
          commit_author: readme-scribe 🤖 <"102756485+Chunnyluny@users.noreply.github.com">
